export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: "#4ec7c7",
    tabIconDefault: "#ccc",
    tabIconSelected: "#4ec7c7",
    yellow: "#F4D35E",
    orange: "#EE964B",
    lightGrey: "#e8e8e8",
    grey: "#646e78",
    white: "#fff",
  },
  dark: {
    text: "#fff",
    background: "#000",
    tint: "#4ec7c7",
    tabIconDefault: "#ccc",
    tabIconSelected: "#4ec7c7",
    yellow: "#F4D35E",
    orange: "#EE964B",
    lightGrey: "#e8e8e8",
    grey: "#646e78",
    white: "#fff",
  },
};
